name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build Linux binary
        run: |
          go build -o tchat-linux main.go

      - name: Build Windows binary
        run: |
          GOOS=windows GOARCH=amd64 go build -o tchat.exe main.go

      - name: Upload Linux binary
        uses: actions/upload-artifact@v4
        with:
          name: tchat-linux
          path: tchat-linux

      - name: Upload Windows binary
        uses: actions/upload-artifact@v4
        with:
          name: tchat-windows
          path: tchat.exe
